
##-----------------------------------------------------------
## Configuração - SPRING DATASOURCE
##-----------------------------------------------------------
server:
  port: 7009
  servlet:
    context-path: /api-rabbitmq
    
spring:
  h2:
    console:
      enabled: true
      path: /h2-console 
      
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  properties:
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
##-----------------------------------------------------------
## Configuração - DATASOURCE
##-----------------------------------------------------------           
  datasource:
    platform: h2
    url: jdbc:h2:file:C:\Eduardo-h2
    driverClassName: org.h2.Driver
    username: sa
    password: admin

##-----------------------------------------------------------
## Configuração - RABBITMQ
##-----------------------------------------------------------
  application:
    name: rabbitmq-producer-basic
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest